{
  c = "clear";
  code = "vim";
  dwc = ''darwin-rebuild check --flake ".#aarch64"'';
  dwb = ''darwin-rebuild switch --flake ".#aarch64"'';
  grep = "grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}";
  ks = "tmux kill-server";
  node-env = "nix-shell -p nodejs_21 bun typescript eslint_d prettierd --command fish";
  g = "git";
  ga = "git add";
  gaa = "git add --all";
  gam = "git am";
  gb = "git branch";
  gbD = "git branch --delete --force";
  gba = "git branch --all";
  gbd = "git branch --delete";
  gbr = "git branch --remote";
  gc = "git commit --verbose";
  gca = "git commit --verbose --all";
  gcam = "git commit --all --message";
  gcb = "git checkout -b";
  gcd = "git checkout $(git_develop_branch)";
  gcf = "git config --list";
  gcl = "git clone --recurse-submodules";
  gcm = "git checkout $(git_main_branch)";
  gco = "git checkout";
  gcor = "git checkout --recurse-submodules";
  gcount = "git shortlog --summary --numbered";
  gcp = "git cherry-pick";
  gcpa = "git cherry-pick --abort";
  gcpc = "git cherry-pick --continue";
  gd = "git diff";
  gds = "git diff --staged";
  gdup = "git diff @{upstream}";
  gf = "git fetch";
  gfa = "git fetch --all --prune --jobs=10";
  gfo = "git fetch origin";
  gl = "git pull";
  glg = "git log --stat";
  glgg = "git log --graph";
  glgga = "git log --graph --decorate --all";
  glgm = "git log --graph --max-count=10";
  glgp = "git log --stat --patch";
  glo = "git log --oneline --decorate";
  globurl = "noglob urlglobber ";
  glod = "git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'";
  glods = "git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset' --date=short";
  glog = "git log --oneline --decorate --graph";
  gloga = "git log --oneline --decorate --graph --all";
  glol = "git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'";
  glola = "git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset' --all";
  glols = "git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset' --stat";
  gluc = "git pull upstream $(git_current_branch)";
  glum = "git pull upstream $(git_main_branch)";
  gm = "git merge";
  gma = "git merge --abort";
  gmom = "git merge origin/$(git_main_branch)";
  gms = "git merge --squash";
  gmum = "git merge upstream/$(git_main_branch)";
  gp = "git push";
  gpf = "git push --force-with-lease --force-if-includes";
  gpr = "git pull --rebase";
  gpristine = "git reset --hard && git clean --force -dfx";
  gpsup = "git push --set-upstream origin $(git_current_branch)";
  gpsupf = "git push --set-upstream origin $(git_current_branch) --force-with-lease --force-if-includes";
  gpu = "git push upstream";
  gpv = "git push --verbose";
  gr = "git remote";
  gra = "git remote add";
  grb = "git rebase";
  grba = "git rebase --abort";
  grbc = "git rebase --continue";
  grbd = "git rebase $(git_develop_branch)";
  grbi = "git rebase --interactive";
  grbm = "git rebase $(git_main_branch)";
  grbo = "git rebase --onto";
  grbom = "git rebase origin/$(git_main_branch)";
  grbs = "git rebase --skip";
  grev = "git revert";
  grh = "git reset";
  grhh = "git reset --hard";
  grm = "git rm";
  grmc = "git rm --cached";
  grmv = "git remote rename";
  groh = "git reset origin/$(git_current_branch) --hard";
  grrm = "git remote remove";
  grs = "git restore";
  grset = "git remote set-url";
  grss = "git restore --source";
  grst = "git restore --staged";
  gru = "git reset --";
  grup = "git remote update";
  grv = "git remote --verbose";
  gsb = "git status --short --branch";
  gsd = "git svn dcommit";
  gsh = "git show";
  gsi = "git submodule init";
  gsps = "git show --pretty=short --show-signature";
  gsr = "git svn rebase";
  gss = "git status --short";
  gst = "git status";
  gsta = "git stash push";
  gstaa = "git stash apply";
  gstall = "git stash --all";
  gstc = "git stash clear";
  gstd = "git stash drop";
  gstl = "git stash list";
  gstp = "git stash pop";
  gsts = "git stash show --text";
  gstu = "gsta --include-untracked";
  gsu = "git submodule update";
  gsw = "git switch";
  gswc = "git switch --create";
  gswd = "git switch $(git_develop_branch)";
  gswm = "git switch $(git_main_branch)";
  gts = "git tag --sign";
  gtv = "git tag | sort -V";
  gunignore = "git update-index --no-assume-unchanged";
  gunwip = "git rev-list --max-count=1 --format=\\\"%s\\\" HEAD | grep -q \\\"--wip--\\\" && git reset HEAD~1";
  gup = "git pull --rebase";
  gupa = "git pull --rebase --autostash";
  gupav = "git pull --rebase --autostash --verbose";
  gupom = "git pull --rebase origin $(git_main_branch)";
  gupomi = "git pull --rebase=interactive origin $(git_main_branch)";
  gupv = "git pull --rebase --verbose";
  gwch = "git whatchanged -p --abbrev-commit --pretty=medium";
  gwip = "git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign --message \\\"--wip-- [skip ci]\\\"";
  gwt = "git worktree";
  gwta = "git worktree add";
  gwtls = "git worktree list";
  gwtmv = "git worktree move";
  gwtrm = "git worktree remove";
} 
