alias as 'aerospace'
alias c 'clear'
alias code 'vim'
alias dwb 'darwin-rebuild switch --flake ".#aarch64"'
alias dwc 'darwin-rebuild check --flake ".#aarch64"'
alias grep 'grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
alias ks 'tmux kill-server'
alias node-shell 'nix shell nixpkgs#{nodejs, typescript, bun}'
alias pn 'pnpm'
alias vimdiff 'nvim -d'
